//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySecureZoneApp.Api.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public System.Guid ActivityLogID { get; set; }
        public System.Guid SessionID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Comments { get; set; }
        public System.DateTime StampDate { get; set; }
    }
}
