//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySecureZoneApp.Api.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminMaintenance
    {
        public System.Guid AdminMaintenanceID { get; set; }
        public int MaintenanceTypeL { get; set; }
        public bool IsActive { get; set; }
        public string MaintenanceDescription { get; set; }
        public System.DateTime StampDate { get; set; }
    
        public virtual lkpMaintenanceType lkpMaintenanceType { get; set; }
    }
}
