//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySecureZoneApp.Api.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentMapping
    {
        public int DocMapID { get; set; }
        public short TyrusCategoryL { get; set; }
        public short TyrusTypeL { get; set; }
        public short MarketingTitleL { get; set; }
    
        public virtual lkpDocumentMarketingType lkpDocumentMarketingType { get; set; }
    }
}
