//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySecureZoneApp.Api.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteTableLink
    {
        public int SiteTableLinkID { get; set; }
        public int SiteL { get; set; }
        public int LinkTableL { get; set; }
        public bool Use { get; set; }
    }
}
