//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySecureZoneApp.Api.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyAnswer
    {
        public System.Guid AnswerID { get; set; }
        public System.Guid AnswerSetID { get; set; }
        public int SurveyID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public System.DateTime DateStamp { get; set; }
        public string Region { get; set; }
    }
}
