//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySecureZoneApp.Api.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyHTML
    {
        public int SurveyContentID { get; set; }
        public int SurveyID { get; set; }
        public int Language { get; set; }
        public string HTML { get; set; }
    
        public virtual SurveyHTML SurveyHTML1 { get; set; }
        public virtual SurveyHTML SurveyHTML2 { get; set; }
    }
}
